### ISSUE TITLE
Create new Generator hierarchy: html-boot

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#121]
## Tasks

- [x] fix semicolon issue
- [x] add a ByteProto faux generator
- [x] add a ByteCode faux generator
- [x] InternalCompiler: simplify proto navigation
