### ISSUE TITLE
Objectos 0.4.1

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#176]
## Features

- [x] #178
- [x] #180
- [x] #181
- [x] #161 
- [x] #187 

## Tasks

- [x] #107
- [x] #121
- [x] fix blog-examples templates

## Bugs

- [x] #177
- [x] #179
- [x] #182

## Documentation

- [x] #189

## Objectos Util #49 

- [ ] use sealed interfaces
- [ ] Growable -> Modifiable
- [ ] improve equals?
- [ ] subList impl
- [ ] UnmodifiableView toArray() methods
