### ISSUE TITLE
Normalize objectos-html package names

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#257]
## Tasks

- [x] merge src/boot/java with src/main/java
- [x] move html.spi.type from objectos-html-spi to objectos-html
- [x] rename html.spi.tmpl to objectos.html.spi
- [x] Move o7.html.spi.type to objectos.html.tmpl package
- [x] Move o7.html.attribute to objectos.html.tmpl package
- [x] Move o7.html.element to objectos.html.tmpl package
- [x] Move AbstractTemplate to objectos.html.HtmlTemplate
