### ISSUE TITLE
Use pathName and pathTo in Docs

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#300]
## Tasks

- [ ] slug and directory should be the same thing
- [ ] prepend pathName with "/docs"
- [ ] have elink use pathTo
- [ ] have ilink use pathTo
