### ISSUE TITLE
Prepare objectos for release 0.1.0

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#37]
Some tasks before releasing:

- [x] move profiles from objectos to incubator
- [x] move away from internal vs. jdk versions
- [x] Normalize objectos.logging pkg names
- [x] NoopLogger -> NoOpLogger
- [x] Event.source() must return String
- [x] Event.key() must return Object
- [x] Event.level()
- [x] Event0
- [x] Event1
- [x] Event2
- [x] Event3
- [x] remove Events and Event legacy constructors
- [x] link javadocs from docs home
- [x] merge toc + home
- [x] README
