### ISSUE TITLE
Introduce objectos-http

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#423]
## Tasks

- [x] remove core-net dependency
- [x] remove core-io depedency
- [x] remove concurrent dependency
- [x] remove fs-testing dependency
- [x] move to objectos-http
- [x] normalize package and module names
