### ISSUE TITLE
HTTP 001: Input / Parse Header phase implementation

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#444]
## Diagram

```mermaid
stateDiagram-v2
[*] --> PARSE_HEADER

INPUT_READ --> PARSE_HEADER
INPUT_READ --> PARSE_HEADER_NAME
INPUT_READ --> PARSE_HEADER_VALUE

PARSE_HEADER: Next header field,\nor body
PARSE_HEADER --> BAD_REQUEST: Buffer full
PARSE_HEADER --> HANDLE
PARSE_HEADER --> PARSE_HEADER_NAME
PARSE_HEADER --> INPUT_READ

PARSE_HEADER_NAME: Header name
PARSE_HEADER_NAME --> BAD_REQUEST: Buffer full
PARSE_HEADER_NAME --> INPUT_READ
PARSE_HEADER_NAME --> PARSE_HEADER_VALUE

PARSE_HEADER_VALUE: Header value
PARSE_HEADER_VALUE --> BAD_REQUEST: Buffer full
PARSE_HEADER_VALUE --> INPUT_READ
PARSE_HEADER_VALUE --> PARSE_HEADER

HANDLE --> [*]

classDef centered text-align:center

class PARSE_HEADER centered
```

## Tasks

- [x] #445
- [x] #446
- [x] #447
- [x] HTTP 001: PARSE_HEADER_NAME --> PARSE_HEADER_VALUE
- [x] HTTP 001: PARSE_HEADER_NAME --> INPUT_READ
- [x] HTTP 001: PARSE_HEADER_NAME --> BAD_REQUEST: Buffer full
- [x] HTTP 001: PARSE_HEADER_VALUE --> PARSE_HEADER
- [x] HTTP 001: PARSE_HEADER_VALUE --> INPUT_READ
- [x] HTTP 001: PARSE_HEADER_VALUE --> BAD_REQUEST: Buffer full
- [ ] HTTP 001: PARSE_HEADER --> HANDLE
