### ISSUE TITLE
objectos-css: styles for a login page

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#459]
Allow styling the objectos-factoring login page.

## Tasks

- [x] type selectors: form
- [x] type selectors: label
- [x] property: min-height
- [x] property: min-width
- [x] integrate objectos.css.IdSelector/ClassSelector w/ objectos-html
- [x] property: flex-direction
- [x] property: justify-content
- [x] #460
- [x] #477
- [x] #480
- [x] Framework: flex-direction / justify-content
- [x] #481
- [x] Framework: padding
- [x] #483
- [x] Framework: margin, width, max-width
- [x] #485
- [x] border related properties
