### ISSUE TITLE
objectos-css: introduce compiled StyleSheet

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#461]
## Tasks

- [x] #462
- [x] #463
- [x] Selfgen CSS: generate StandardName.byOrdinal() method
- [x] #464
- [x] #465
- [x] #466
- [x] #467
- [x] #468
- [x] #469
- [x] #470
- [x] #471
- [x] #474
- [x] #475
- [x] #476
- [x] Compiled StyleSheet: support nl after style rule
- [x] #472
- [x] #473
- [ ] Compiled StyleSheet: use Keyword instead of StandardName
