### ISSUE TITLE
Objectos 0.3.0 Milestone

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos#96]
## Projects

- [x] #49
- [x] #33 

## Documentation

- [x] intro
- [x] Array utilities
- [x] Collections API
- [x] Collections API: of methods
- [x] Collections API: Limitations
- [x] Release notes

## Objectos Util

- [x] core-array
- [x] core-collection
- [x] core-util
- [x] core-set
- [x] core-map
- [x] merge/remove Latest related types
- [x] remove MutableX.create() methods
- [x] package-info javadocs
- [x] classes javadocs
- [x] UnmodifiableCollection
- [x] Mutable -> Growable
- [x] #54 
- [x] #103
